# -*- coding: utf-8 -*-
"""Corporate_Finance_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgJc7nZAglDjSHuK4_npPP6MnoS84yf2
"""

import yfinance as yf

msft = yf.Ticker("MSFT")
data = msft.history(period="15y")
data.to_csv("microsoft_stock_data.csv")

print("Download complete! First 5 rows:")
print(data.head())

data.describe()
data = data.reset_index()

# SMA 20day
data['SMA_20'] = data['Close'].rolling(window=20).mean()

# RSI 14day reff
delta = data['Close'].diff()
gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
rs = gain / loss
data['RSI'] = 100 - (100 / (1 + rs))

# MACD
exp1 = data['Close'].ewm(span=12, adjust=False).mean()
exp2 = data['Close'].ewm(span=26, adjust=False).mean()
data['MACD'] = exp1 - exp2

data.dropna(inplace=True)
df= data[['Close', 'High', 'Low', 'Volume', 'SMA_20', 'RSI', 'MACD']]
df

df.info()

import matplotlib.pyplot as plt


fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(15, 12), sharex=True,
                                         gridspec_kw={'height_ratios': [3, 1, 1, 1]})

# 1. Main Price Plot (Close, High, Low, SMA)
ax1.plot(df.index, df['Close'], label='Close', color='blue', alpha=0.8)
ax1.plot(df.index, df['SMA_20'], label='SMA 20', color='orange', linestyle='--')
ax1.fill_between(df.index, df['Low'], df['High'], color='gray', alpha=0.2, label='High-Low Range')
ax1.set_title('Stock Price & Indicators')
ax1.legend(loc='upper left')
ax1.set_ylabel('Price ($)')

# Volume Plot
ax2.bar(df.index, df['Volume'], color='gray', alpha=0.5)
ax2.set_ylabel('Volume')

# RSI Plot
ax3.plot(df.index, df['RSI'], color='purple')
ax3.axhline(70, color='red', linestyle='--', alpha=0.5) # overbought line
ax3.axhline(30, color='green', linestyle='--', alpha=0.5) # oversold line
ax3.set_ylabel('RSI')
ax3.set_ylim(0, 100)

# MACD Plot
ax4.plot(df.index, df['MACD'], color='black', label='MACD')
ax4.axhline(0, color='gray', linestyle='-', linewidth=0.5)
ax4.set_ylabel('MACD')

plt.xlabel('Date')
plt.tight_layout()
plt.show()

import tensorflow as tf

print(tf.config.list_physical_devices('GPU'))

from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df)
training_size = int(len(scaled_data) * 0.65)
train_data = scaled_data[0:training_size, :]
test_data = scaled_data[training_size:len(scaled_data), :]

import numpy as np

def create_multivariate_dataset(dataset, time_step=1):
    dataX, dataY = [], []
    for i in range(len(dataset) - time_step - 1):
        dataX.append(dataset[i:(i + time_step), :])
        dataY.append(dataset[i + time_step, 0])
    return np.array(dataX), np.array(dataY)

X_train, y_train = create_multivariate_dataset(train_data, 100)
X_test, y_test = create_multivariate_dataset(test_data, 100)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential([
    LSTM(100, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])),
    Dropout(0.2),

    LSTM(100, return_sequences=False),
    Dropout(0.2),

    Dense(25),
    Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error')

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

train_predict = model.predict(X_train)
test_predict = model.predict(X_test)

def inverse_transform_only_close(scaler, predictions, n_features):
    dummy = np.zeros((len(predictions), n_features))
    dummy[:, 0] = predictions.flatten()
    return scaler.inverse_transform(dummy)[:, 0]


n_feats = 7
train_predict_real = inverse_transform_only_close(scaler, train_predict, n_feats)
test_predict_real = inverse_transform_only_close(scaler, test_predict, n_feats)

y_train_real = inverse_transform_only_close(scaler, y_train, n_feats)
y_test_real = inverse_transform_only_close(scaler, y_test, n_feats)

import math
from sklearn.metrics import mean_squared_error, r2_score


train_rmse = math.sqrt(mean_squared_error(y_train_real, train_predict_real))
test_rmse = math.sqrt(mean_squared_error(y_test_real, test_predict_real))


r2 = r2_score(y_test_real, test_predict_real)

print(f"Train RMSE: ${train_rmse:.2f}")
print(f"Test RMSE: ${test_rmse:.2f}")
print(f"R2 Score: {r2:.4f}")

import numpy as np
import pandas as pd

last_100_days = test_data[-100:].reshape(1, 100, 7)
temp_input = list(last_100_days[0])
lst_output = []

for i in range(30):
    current_input = np.array(temp_input[-100:]).reshape(1, 100, 7)


    yhat = model.predict(current_input, verbose=0)


    last_row = temp_input[-1].copy()
    last_row[0] = yhat[0][0]

    lst_output.append(yhat[0][0])
    temp_input.append(last_row)


dummy_april = np.zeros((30, 7))
dummy_april[:, 0] = np.array(lst_output)
april_forecast_prices = scaler.inverse_transform(dummy_april)[:, 0]

monthly_average = np.mean(april_forecast_prices)
monthly_max = np.max(april_forecast_prices)
monthly_min = np.min(april_forecast_prices)

print(f"--- April 2026 Forecast Summary ---")
print(f"Average Predicted Price: ${monthly_average:.2f}")
print(f"Predicted Monthly High:  ${monthly_max:.2f}")
print(f"Predicted Monthly Low:   ${monthly_min:.2f}")

import matplotlib.pyplot as plt

last_date = pd.to_datetime("2026-03-31")
april_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=30)
plt.figure(figsize=(12, 6))


plt.plot(april_dates, april_forecast_prices, label='April Forecast', color='orange', linewidth=2)

plt.axhline(y=monthly_average, color='red', linestyle='--', alpha=0.5,
            label=f'Monthly Avg: ${monthly_average:.2f}')

plt.title("Microsoft (MSFT) Predicted Price: April 2026")
plt.xlabel("Date")
plt.ylabel("Price (USD)")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

import pandas as pd
import numpy as np


prediction_dates = pd.date_range(start="2026-04-01", periods=30)

n_features = 7
dummy = np.zeros((len(lst_output), n_features))
dummy[:, 0] = np.array(lst_output).flatten()
month_prices = scaler.inverse_transform(dummy)[:, 0]


april_forecast = pd.DataFrame({
    'Date': prediction_dates,
    'Predicted_Price': month_prices
})

april_forecast['Predicted_Price'] = april_forecast['Predicted_Price'].round(2)
april_forecast.columns = ['Date', 'Predicted Close Price (USD)']
print(april_forecast.to_string(index=False))

